# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_chronos_wrappers", use_symbols = TRUE, package_name = "chronos")

#' @docType package
#' @usage NULL
#' @useDynLib chronos, .registration = TRUE
NULL

chronos_rs <- function(times) .Call(wrap__chronos_rs, times)


# nolint end
