# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_timeless_wrappers", use_symbols = TRUE, package_name = "timeless")

#' @usage NULL
#' @useDynLib timeless, .registration = TRUE
NULL

parse_guess_rs <- function(times) .Call(wrap__parse_guess_rs, times)

parse_datetime_rs <- function(times, formats, out_format) .Call(wrap__parse_datetime_rs, times, formats, out_format)

parse_date_rs <- function(times, formats, out_format) .Call(wrap__parse_date_rs, times, formats, out_format)

parse_epoch_rs <- function(times, out_format) .Call(wrap__parse_epoch_rs, times, out_format)

parse_epoch_i64_rs <- function(times, out_format) .Call(wrap__parse_epoch_i64_rs, times, out_format)


# nolint end
